<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.platform</groupId>
        <artifactId>data-platform-pro</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>data-common</artifactId>
    <packaging>pom</packaging>
    <name>data-common</name>

    <modules>
        <module>data-common-core</module>
        <module>data-common-jpa</module>
        <module>data-common-redis</module>
        <module>data-common-security</module>
        <module>data-common-ds</module>
        <module>data-common-om</module>
    </modules>
</project>
