apiVersion: v1
kind: Namespace
metadata:
  name: data-platform
  labels:
    app.kubernetes.io/part-of: data-platform-pro
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-platform-quota
  namespace: data-platform
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    services.loadbalancers: "2"
