apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: data-platform
type: Opaque
stringData:
  # Doris
  doris-user: root
  doris-password: "root"
  # Redis
  redis-password: ""
  # DolphinScheduler
  ds-token: "default_token"
  # OpenMetadata
  om-jwt-token: "eyJraWQiOiJHYjM4OFEtUEZ5Q1Z4Nk4tVHJia2ciLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.fake-token-for-dev"
  om-webhook-secret: "data-platform-wh-secret"
  postgres-om-user: openmetadata
  postgres-om-password: openmetadata_pass
  # JWT for gateway auth
  jwt-secret: "data-platform-jwt-secret-key-2026"
