import { readFileSync, writeFileSync } from 'fs'

const FILES = [
  'src/views/system/Services.vue','src/views/system/Projects.vue','src/views/system/Knowledge.vue',
  'src/views/system/Models.vue','src/views/system/Users.vue','src/views/system/License.vue','src/views/system/Roles.vue',
  'src/views/agent/Apps.vue','src/views/agent/Knowledge.vue','src/views/agent/Planning.vue','src/views/agent/Square.vue','src/views/agent/Workbench.vue',
  'src/views/lab/ModelConfig.vue','src/views/lab/Gov.vue','src/views/lab/Ecommerce.vue','src/views/lab/Datasources.vue','src/views/lab/Overview.vue',
  'src/views/search/Business.vue','src/views/search/Model.vue','src/views/search/Search.vue',
  'src/views/docs/Templates.vue','src/views/docs/Mine.vue'
]

// noise: FFFD + "'" immediately followed by '"'  => the ' is garbage (e.g. label="知识库名称")
// applied first so word rules only need to handle FFFD (+ optional ':' noise)
const PRE = [
  [/\uFFFD'"/g, '\uFFFD"']
]

const G = [
  // sentence end inside </p>
  [/([\u4e00-\u9fa5])\uFFFD(<\/p>)/g, '$1。$2'],
  // 「 + lost $
  [/\uFFFD"\{/g, '「${'],
  [/\}\uFFFD\.\.\./g, '}」...'],
  [/unit="\uFFFD:?"/g, 'unit="个"'],
  // time range options
  [/\uFFFD 30 \uFFFD:\?/g, '近 30 天'],
  [/\uFFFD 90 \uFFFD:\?/g, '近 90 天'],
  [/\uFFFD 180 \uFFFD:\?/g, '近 180 天'],
  [/\uFFFD 1 \uFFFD:\?/g, '近 1 年'],
  [/\uFFFD 7 \uFFFD:\?/g, '近 7 天'],
  [/本年\uFFFD:?/g, '本年度'],
  // specific phrases
  [/SQL开发助\uFFFD 4/g, 'SQL开发助手-4'],
  [/发布\uFFFD API/g, '发布为 API'],
  [/独立页\uFFFD/g, '独立页面'],
  [/发布到应用广\uFFFD/g, '发布到应用广场'],
  [/合格数据\uFFFD<\/ 总数据量/g, '合格数据 ÷ 总数据量'],
  [/查询最\uFFFD\?天/g, '查询最近30天'],
  [/渠道\uFFFD\?/g, '渠道是'],
  [/APP \uFFFD\?\*/g, 'APP 端**'],
  [/小程\uFFFD\?-/g, '小程序 -'],
  [/总销售额\uFFFD /g, '总销售额的 '],
  [/数据量：\uFFFD /g, '数据量：约 '],
  [/平\uFFFD /g, '平均 '],
  [/Chunk \uFFFD/g, 'Chunk 数'],
  [/工具\uFFFD'\+/g, '工具栏 +'],
  [/状态筛\uFFFD:?/g, '状态筛选'],
  [/消息\uFFFD -->/g, '消息） -->'],
  [/已\uFFFD \{\{/g, '已选 {{'],
  [/当前用户\uFFFD/g, '当前用户数'],
  // status words
  [/运行状\uFFFD:?/g, '运行状态'],
  [/构建状\uFFFD:?/g, '构建状态'],
  [/项目状\uFFFD:?/g, '项目状态'],
  [/共享状\uFFFD:?/g, '共享状态'],
  [/状\uFFFD:?/g, '状态'],
  [/待运\uFFFD/g, '待运行'],
  [/运行\uFFFD:?/g, '运行中'],
  [/已停\uFFFD:?/g, '已停止'],
  [/已完\uFFFD:?/g, '已完成'],
  [/已失\uFFFD/g, '已失败'],
  [/多模\uFFFD:?/g, '多模型'],
  [/负责\uFFFD:?/g, '负责人'],
  [/已构\uFFFD:?/g, '已构建'],
  [/待构\uFFFD:?/g, '待构建'],
  [/构建\uFFFD:?/g, '构建中'],
  [/已发\uFFFD:?/g, '已发布'],
  [/最新发\uFFFD:?/g, '最新发布'],
  [/评分最\uFFFD:?/g, '评分最高'],
  [/已下\uFFFD:?/g, '已下线'],
  [/调试\uFFFD:?/g, '调试中'],
  [/已锁\uFFFD:?/g, '已锁定'],
  [/已验\uFFFD:?/g, '已验收'],
  [/已归\uFFFD:?/g, '已归档'],
  [/进行\uFFFD:?/g, '进行中'],
  [/已删\uFFFD/g, '已删除'],
  [/已刷\uFFFD/g, '已刷新'],
  [/已过\uFFFD/g, '已过期'],
  [/已启\uFFFD/g, '已启用'],
  [/未启\uFFFD/g, '未启用'],
  // common nouns
  [/对话\uFFFD/g, '对话框'],
  [/知识库检\uFFFD/g, '知识库检索'],
  [/知识\uFFFD/g, '知识库'],
  [/姓\uFFFD/g, '姓名'],
  [/名\uFFFD:?/g, '名称'],
  [/长\uFFFD:?/g, '长度'],
  [/满意\uFFFD:?/g, '满意度'],
  [/供应\uFFFD:?/g, '供应商'],
  [/提供\uFFFD:?/g, '提供商'],
  [/开放平\uFFFD:?/g, '开放平台'],
  [/阿里云百\uFFFD:?/g, '阿里云百炼'],
  [/已连\uFFFD:?/g, '已连接'],
  [/未连\uFFFD:?/g, '未连接'],
  [/连通性测\uFFFD:?/g, '连通性测试'],
  [/连通\uFFFD/g, '连通性'],
  [/新步\uFFFD/g, '新步骤'],
  [/列\uFFFD/g, '列表'],
  [/个工\uFFFD/g, '个工具'],
  [/个应\uFFFD/g, '个应用'],
  [/次调\uFFFD/g, '次调用'],
  [/调用\uFFFD/g, '调用量'],
  [/调\uFFFD/g, '调试'],
  [/测\uFFFD/g, '测试'],
  [/工具\uFFFD:?/g, '工具数'],
  [/知识库数\uFFFD:?/g, '知识库数量'],
  [/智能体数\uFFFD:?/g, '智能体数量'],
  [/智能体平\uFFFD/g, '智能体平台'],
  [/智能体应\uFFFD/g, '智能体应用'],
  [/智能\uFFFD:?/g, '智能体'],
  [/文档\uFFFD:?/g, '文档数'],
  [/分片\uFFFD:?/g, '分片数'],
  [/浏览\uFFFD/g, '浏览量'],
  [/浏\uFFFD/g, '浏览'],
  [/次使\uFFFD/g, '次使用'],
  [/次查\uFFFD/g, '次查询'],
  [/次\uFFFD:?/g, '次数'],
  [/模\uFFFD/g, '模板'],
  [/示例内\uFFFD/g, '示例内容'],
  [/开箱即\uFFFD/g, '开箱即用'],
  [/文档质\uFFFD/g, '文档质量'],
  [/注意事\uFFFD/g, '注意事项'],
  [/解\uFFFD/g, '解析'],
  [/检\uFFFD/g, '检索'],
  [/可视化图\uFFFD/g, '可视化图表'],
  [/整合与回\uFFFD/g, '整合与回复'],
  [/新应\uFFFD/g, '新应用'],
  [/新用\uFFFD/g, '新用户'],
  [/发\uFFFD/g, '发送'],
  [/请输\uFFFD/g, '请输入'],
  [/数据源管\uFFFD/g, '数据源管理'],
  [/数据源类\uFFFD:?/g, '数据源类型'],
  [/数据源用途说\uFFFD:?/g, '数据源用途说明'],
  [/说\uFFFD:?/g, '说明'],
  [/编辑数据\uFFFD/g, '编辑数据源'],
  [/新增数据\uFFFD/g, '新增数据源'],
  [/表数\uFFFD/g, '表数量'],
  [/label="数据\uFFFD:?"/g, 'label="数据量"'],
  [/普通用\uFFFD/g, '普通用户'],
  [/超级管理\uFFFD/g, '超级管理员'],
  [/菜单\uFFFD:?/g, '菜单数'],
  [/存\uFFFD/g, '存在'],
  [/配置已保\uFFFD/g, '配置已保存'],
  [/模型已更\uFFFD/g, '模型已更新'],
  [/模型已添\uFFFD/g, '模型已添加'],
  [/模型已删\uFFFD/g, '模型已删除'],
  [/模型已保\uFFFD/g, '模型已保存'],
  [/角色已保\uFFFD/g, '角色已保存'],
  [/项目已保\uFFFD/g, '项目已保存'],
  [/用户已保\uFFFD/g, '用户已保存'],
  [/成员已移\uFFFD/g, '成员已移除'],
  [/角色\uFFFD</g, '角色：<'],
  [/全\uFFFD(\s*<\/el-checkbox>)/g, '全选$1'],
  [/不同的权\uFFFD/g, '不同的权限'],
  [/较上\uFFFD/g, '较上周'],
  [/开始日\uFFFD/g, '开始日期'],
  [/条记\uFFFD/g, '条记录'],
  [/脏数据比\uFFFD/g, '脏数据比例'],
  [/家庭户规\uFFFD/g, '家庭户规模'],
  [/所属区\uFFFD/g, '所属区县'],
  [/区县\uFFFD/g, '区县级'],
  [/(北京|上海|广州|深圳|杭州|成都)\uFFFD/g, '$1市'],
  [/(东城|西城|朝阳|海淀|丰台)\uFFFD/g, '$1区'],
  [/来源地权\uFFFD/g, '来源地权重'],
  [/入学\uFFFD\?\(/g, '入学率('],
  [/办结率目\uFFFD\?\(/g, '办结率目标('],
  [/右侧内容\uFFFD/g, '右侧内容区'],
  [/数据导出\uFFFD/g, '数据导出中'],
  [/共找\uFFFD/g, '共找到'],
  [/条业务数\uFFFD/g, '条业务数据'],
  [/条结\uFFFD/g, '条结果'],
  [/筛选条\uFFFD/g, '筛选条件'],
  [/搜索条\uFFFD/g, '搜索条件'],
  [/表资\uFFFD/g, '表资产'],
  [/按热度排\uFFFD/g, '按热度排序'],
  [/新时间排\uFFFD/g, '新时间排序'],
  [/排\uFFFD/g, '排序'],
  [/不含退\uFFFD/g, '不含退款'],
  [/有效订单\uFFFD/g, '有效订单数'],
  [/复购\uFFFD/g, '复购率'],
  [/的客户占\uFFFD/g, '的客户占比'],
  [/营指标汇\uFFFD/g, '营指标汇总'],
  [/理层级下\uFFFD/g, '理层级下钻'],
  [/量渠道维\uFFFD/g, '量渠道维度'],
  [/经营驾驶\uFFFD/g, '经营驾驶舱'],
  [/售专题看\uFFFD/g, '售专题看板'],
  [/值分层分\uFFFD/g, '值分层分析'],
  [/对比分\uFFFD/g, '对比分析'],
  [/并返回结\uFFFD/g, '并返回结果'],
  [/编写和优\uFFFD/g, '编写和优化'],
  [/的商品明\uFFFD/g, '的商品明细'],
  [/合销售指\uFFFD/g, '合销售指标'],
  [/层经营看\uFFFD/g, '层经营看板'],
  [/关联主\uFFFD/g, '关联主题'],
  [/款原因说\uFFFD/g, '款原因说明'],
  [/步支付记\uFFFD/g, '步支付记录'],
  [/段取值范\uFFFD/g, '段取值范围'],
  [/主键唯一\uFFFD/g, '主键唯一性'],
  [/格式合法\uFFFD/g, '格式合法性'],
  [/金额一致\uFFFD/g, '金额一致性'],
  [/唯一\uFFFD/g, '唯一性'],
  [/一致\uFFFD/g, '一致性'],
  [/合法\uFFFD/g, '合法性'],
  [/客单\uFFFD/g, '客单价'],
  [/会员活跃\uFFFD/g, '会员活跃率'],
  [/小程\uFFFD/g, '小程序'],
  [/商品类目\uFFFD/g, '商品类目数'],
  [/日均订单\uFFFD/g, '日均订单量'],
  [/每月一\uFFFD/g, '每月一次'],
  [/每季度一\uFFFD/g, '每季度一次'],
  [/退换货\uFFFD/g, '退换货率'],
  [/销售数据概\uFFFD/g, '销售数据概览'],
  [/概\uFFFD/g, '概览'],
  [/销售趋\uFFFD/g, '销售趋势'],
  [/趋\uFFFD/g, '趋势'],
  [/目销售占\uFFFD/g, '目销售占比'],
  [/销售数\uFFFD/g, '销售数据'],
  [/女\uFFFD/g, '女性'],
  [/男\uFFFD/g, '男性'],
  [/系统提示\uFFFD/g, '系统提示词'],
  [/提示\uFFFD/g, '提示词'],
  [/相似度阈\uFFFD/g, '相似度阈值'],
  [/阈\uFFFD/g, '阈值'],
  [/相似\uFFFD/g, '相似度'],
  [/消息\uFFFD/g, '消息数'],
  [/最大迭代次\uFFFD:?/g, '最大迭代次数'],
  [/请选择左侧智能体进行配\uFFFD:?/g, '请选择左侧智能体进行配置'],
  [/功\uFFFD:?/g, '功能'],
  [/搜索和分\uFFFD/g, '搜索和分类'],
  [/按领域统\uFFFD/g, '按领域统计'],
  [/统\uFFFD/g, '统计'],
  [/实验页\uFFFD/g, '实验页面'],
  [/我是一\uFFFD/g, '我是一个'],
  [/机器码信\uFFFD/g, '机器码信息'],
  [/信\uFFFD/g, '信息'],
  [/卡\uFFFD/g, '卡片'],
  [/许可证管\uFFFD/g, '许可证管理'],
  [/授权码管\uFFFD/g, '授权码管理'],
  [/许可证编\uFFFD/g, '许可证编号'],
  [/编\uFFFD/g, '编号'],
  [/版本\uFFFD:?/g, '版本号'],
  [/用户数限\uFFFD/g, '用户数限制'],
  [/限\uFFFD/g, '限制'],
  [/已用模块\uFFFD/g, '已用模块数'],
  [/服务\uFFFD/g, '服务数'],
  [/使用\uFFFD:?/g, '使用率'],
  [/实例\uFFFD:?/g, '实例数'],
  [/关键\uFFFD/g, '关键词'],
  [/监听端\uFFFD/g, '监听端口'],
  [/缓存命中\uFFFD/g, '缓存命中率'],
  [/合格\uFFFD/g, '合格率'],
  [/任\uFFFD/g, '任务'],
  [/占\uFFFD/g, '占比'],
  [/} \uFFFD</g, '} 个<']
]

const PER_FILE = {
  'src/views/system/Roles.vue': [
    [/用户\uFFFD:?/g, '用户数']
  ],
  'src/views/lab/Ecommerce.vue': [
    [/label="销\uFFFD:?"/g, 'label="销量"'],
    [/用户\uFFFD</g, '用户数</'],
    [/订单\uFFFD/g, '订单量']
  ],
  'src/views/agent/Workbench.vue': [
    [/销\uFFFD/g, '销售']
  ],
  'src/views/lab/Datasources.vue': [
    [/用户\uFFFD/g, '用户名'],
    [/开\uFFFD:?/g, '开发']
  ],
  'src/views/system/Users.vue': [
    [/用户\uFFFD/g, '用户名']
  ]
}

let totalBefore = 0, totalAfter = 0
for (const f of FILES) {
  let c = readFileSync(f, 'utf8')
  const before = (c.match(/\uFFFD/g) || []).length
  totalBefore += before
  if (!before) continue
  for (const [re, to] of PRE) c = c.replace(re, to)
  for (const [re, to] of G) c = c.replace(re, to)
  for (const [re, to] of (PER_FILE[f] || [])) c = c.replace(re, to)
  const after = (c.match(/\uFFFD/g) || []).length
  totalAfter += after
  writeFileSync(f, c, 'utf8')
  console.log(`${f}: ${before} -> ${after}`)
  if (after) {
    c.split(/\r?\n/).forEach((l, i) => { if (l.includes('\uFFFD')) console.log(`   L${i + 1}: ${l.trim().slice(0, 150)}`) })
  }
}
console.log(`\nTOTAL: ${totalBefore} -> ${totalAfter}`)
